### ISSUE TITLE
[Feature request]: Dark Mode 

### ISSUE THREAD

**Issue by octoper** [laravel-zero/laravel-zero.com#2]
As @billmn & @owenvoke suggested it think it will be nice to add a dark mode for the website

**Comment by billmn** [comment]
We can consider to switch to Light/Dark Mode using a Light Switch. This allows a user to choose which mode to use regardless of the mode used on their operating system.

**Comment by octoper** [comment]
@billmn Yeah I agree!

**Comment by owenvoke** [comment]
Yeah, I guess it could default to the `prefers-color-scheme` value and then allow toggling after with a cookie/local storage. :+1:

**Comment by khatabwedaa** [comment]
### Work in progress

You can check it [Here](https://github.com/khatabwedaa/laravel-zero.com/tree/feat/dark-mode)

![Screenshot from 2021-01-24 10-36-07](https://user-images.githubusercontent.com/38974561/105625211-2957e780-5e30-11eb-942d-cea622939973.png)
![Screenshot from 2021-01-24 10-36-01](https://user-images.githubusercontent.com/38974561/105625213-2a891480-5e30-11eb-94a0-f33c686a50d5.png)

**Comment by nunomaduro** [comment]
This would be dope for Pest too.

**Comment by khatabwedaa** [comment]
@nunomaduro of course, @octoper Do you have an idea for how we can implement a toggle button. I'm not that good on js 😅.

**Comment by octoper** [comment]
> This would be dope for Pest too.

@nunomaduro I'm working on that!

**Comment by octoper** [comment]
@khatabwedaa Yeah I can help, if you are ready with the dark mode styling just make a pull request with your changes and I will help you with the JS toggle!

**Comment by khatabwedaa** [comment]
@octoper opened!
